### ISSUE TITLE
WLED and Ubiquiti U7 pro incompatibility/problem?

### ISSUE THREAD

**Issue by wila91** [Aircoookie/WLED#4517]
https://github.com/user-attachments/assets/ff5bfc1e-2d54-4b5f-9a36-41c9703a4be3

### What happened?

Im runing WLED  on ESP32 and its been running good for guite some time. **Just now updated my old asus wifi to Ubiquiti U7 pro**. There has been reports that there is issues whit IoT devises so this problem that im having is moastlikely **something to do whit Ubiquiti U7 pro not just WLED**. 
So the bug it self is that when ESP32 WLED is connected to Ubiquiti U7 PRO WLED will not respond to commands at all and will say connection to light failed. it will be unresponssive for some seconds untill it will be normal for about 10s and then it will hapen again in a loop.
Also if WLED devise is connected to Ubiquiti U7 PRO all effects will stop and resume after the frize. This will loop also. Video off the problem

**Any ideas what could be causing this?**

### To Reproduce Bug

Ubiquiti U7 PRO and ESP32 connected. Running a effect will make the problem easy to see but you will not be able to controll anything when when the device gets stuck

### Expected Behavior

effect should not stop and conrolling the light should be possible

### Install Method

Binary from WLED.me

### What version of WLED?

Nightly Release 20250124 and WLED 0.14.0 "Hoshi" have the same issue

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell

```

### Anything else?

![Image](https://github.com/user-attachments/assets/dd4fcbce-6a93-40cf-8a6d-1330c0ce93ab)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by wila91** [comment]
did some testing and its possible to ping the device but it's not possible to control

**Comment by wila91** [comment]
The video shows how at about 8 seconds the lights freeze and after a while they continue again (at about 14 seconds) and then freeze again at 25 seconds... the same thing continues. Whit my old wifi ap everything is works whitout problems

**Comment by blazoncek** [comment]
There are plenty of WiFi settings in UniFi controller regarding enabled features. Please unselect all incompatible features like fast roaming, BSSID transition, meshing, etc.

**Comment by netmindz** [comment]
Please can you also try the _V4 bin from the nightly to see if that's any better/different please?

**Comment by wila91** [comment]
> There are plenty of WiFi settings in UniFi controller regarding enabled features. Please unselect all incompatible features like fast roaming, BSSID transition, meshing, etc.

I have tried many different WiFi settings... roaming, BSSID transition, meshing are all off. There is "Enhanced IoT Connectivity" and i have tried whit that on and off. I have tried changing all possible settings that I thought might affect or help.

I have also tried their latest and few others EA  fimawires (latest 7.2.22) for u7pro

**Comment by wila91** [comment]
> Please can you also try the _V4 bin from the nightly to see if that's any better/different please?

Tested _V4 bin from the nightly and its the same. No change

**Comment by wila91** [comment]
10 seconds working 7 seconds stuck. 

The speed remains the same whether there is a lot of WiFi traffic or not. Even if I turn off all other frequencies, the same thing remains. Only when I turn off the connection from the U7 Pro does the problem disappears. If I connect the WLED to my old Access Point and then its ok for the U7 Pro to be on just cant be connetion between u7pro and WLED.

**Comment by wila91** [comment]
Had my 3 WLEDS running chase effect at the same time and I could see them all. They were getting stuck out of sync but at the same rate. So one or two could be stuck and others were running.

**Comment by wila91** [comment]
Didn't mean to close

**Comment by blazoncek** [comment]
I remember having issues on UniFi APs (WiFi5) which were resolved by fixing 2.4GHz channels on each of them and trying to get them as little overlapping as possible.

**Comment by wila91** [comment]
> I remember having issues on UniFi APs (WiFi5) which were resolved by fixing 2.4GHz channels on each of them and trying to get them as little overlapping as possible.

I only run one AP and the neighbors' WiFi can barely reach inside my house. I have Zigbee devices but they are ZigBee channel 11 (around wifi ch 1) and my 2.4GHz Wifi network is ch 13.

Dont know how to make it better

**Comment by blazoncek** [comment]
> my 2.4GHz Wifi network is ch 13

Move away from channel 13. It is known to cause issues. Use 1, 6, or 11.

**Comment by wila91** [comment]
changed to 11. And its still the same

the channel has changed several times. It has mostly been on automatic, although now that I have tested more I have also changed manually

**Comment by wila91** [comment]
![Image](https://github.com/user-attachments/assets/5a30628d-f042-4e3b-821b-7722e1d48b49)

Connention should not be that bad...
And ping was good ealyer and didn't stop when leds get stuck

**Comment by wila91** [comment]
![Image](https://github.com/user-attachments/assets/fae84b4c-6668-4b58-aee5-96518f44afd3)

When the LEDs get stuck the arvage FPS shows 0

**Comment by netmindz** [comment]
> > Please can you also try the _V4 bin from the nightly to see if that's any better/different please?
> 
> Tested _V4 bin from the nightly and its the same. No change

Can you also try a full erase and install of that env from platformIO so you also get the right bootloader please?

**Comment by wila91** [comment]
After I completely reinstalled all 3 started working normally. Shouldn't have trusted the OTA

OTA is just so easy to use whitout having to disassemble anything.

I don't understand how change of the access point made all the problems to surface.

Anyhow. Now the lights are working again!

Thanks!

**Comment by netmindz** [comment]
I'm not 100% clear of exactly what is in the bootloader, but it does seem to do much more than just load the app

**Comment by blazoncek** [comment]
> I'm not 100% clear of exactly what is in the bootloader, but it does seem to do much more than just load the app

It also initialises the hardware.

**Comment by intermittech** [comment]
Next time something you could try is taking out or changing the configured NTP server, I've seen reports of similar freezes before caused by an unavailable or flaky NTP server being configured.

**Comment by wila91** [comment]
NTP server might have been a issue. I had one setup and my new IoT network did not have internet connection. 

Let's see if I have time and enthusiasm, I might test it by setting up an NTP server now and see that happens.

**Comment by wila91** [comment]
> Next time something you could try is taking out or changing the configured NTP server, I've seen reports of similar freezes before caused by an unavailable or flaky NTP server being configured.

Turned on "get time from NTP server" and its freezing again. My IoT network does not have internet access so it can't connect

**Comment by blazoncek** [comment]
> My IoT network does not have internet access so it can't connect

What's the purpose of getting time then? Do you have private NTP server? If not then disable NTP. You will not be able to use internal timers or scheduled presets.

**Comment by wila91** [comment]
Now I turned on NTP just for the sake of experimenting. Previously, I had use for it on the old WiFi and that's why it was turned on. When I switched to the new WiFi, I didn't even think about that setting and its possible effect on the lights.

NTP is off and there is no intention to turn it on.

To avoid someone else potentially having a similar problem, would it make sense to have an error message stating that the NTP server cannot be contacted and this may cause a hang/freezing? (or figure out why it hangs/freezes and fix it?)

**Comment by OberfragGER** [comment]
I know this is a year old but i will update my strange Information.

So - currently i have a FritzBox WiFi Mesh including pihole. After i turned the NTP-Servers inside pihole off, all my IoT-Devices, especially Wemos D1 Mini Pro are stable like it should. I also have a Wemos WLED Device (various FW from 14.0 to 15.3). With the FritzWifi its running stable!

When i switch to the Unifi IoT Wifi (2.4 GHz) the Devices are becomming very unstable and boor up every 1-2 Minutes...or less, when im connected to the U7 Pro. When the same Device is connected to the UK Ultra- its stable!

What the hell is that? Thats pretty odd!

**Comment by DedeHai** [comment]
may be related to this: https://github.com/wled/WLED/pull/5438
please try the bin file from that PR to check if it fixes something.

**Comment by DedeHai** [comment]
@OberfragGER the bins are a bit hidden under "checks" but each PR has compiled files:
https://github.com/wled/WLED/actions/runs/23403502663?pr=5438

**Comment by OberfragGER** [comment]
@DedeHai  - Thanks a lot. I commented the issue there. Connection is now working, but no frontend now.

**Comment by jonny190** [comment]
Confirming this is a U7 firmware problem — with a fix (firmware downgrade).

Same symptom here: ESP32 WLED strips on a Ubiquiti U7-Pro-Max, associating then dropping every ~10–15 s in a loop ("connection failed", effects freeze/resume). Multiple WLED versions (0.14.x and 0.15.x) and ~7 different devices all did it — so it's not WLED-version- or device-specific.

After a fairly exhaustive diagnosis I'm confident it's the U7 firmware breaking the WPA2 4-way handshake with Espressif/ESP clients. From the UniFi AP logs the repeating pattern is:

WPA: sending 3/4 msg of 4-Way Handshake
WPA: sending 3/4 msg of 4-Way Handshake     <- AP re-sends 3/4; the ESP never returns 4/4
802.11: disassociated
sta_dc_reason "sta left", wpa_auth_failures: 1, deauth_reason 15 (= 4-Way Handshake timeout)

The ESP CPU never reboots (WLED uptime keeps climbing) — only the WiFi link cycles — which is exactly the "freezes, recovers ~10s, repeats" behaviour.

How I proved it's the AP firmware (not WLED / power / RF / DNS):
  - Moved the same devices to a U6-Pro (WiFi 6) and a UAP-AC-Pro (WiFi 5) → 0 disconnects in 5 min, totally stable.
  - Ruled out power (three separate PSUs all flapped identically), channel congestion (2.4 GHz ~8% airtime, −71 dBm noise), roaming, and IPv6/RA/DNS (made the VLAN fully RA-free — still cycled; and the ~10–15 s cycle is far faster than RAs even arrive).
  - Downgrading the U7-Pro-Max firmware → 0 disconnects, stable back on the U7. 

So this is a U7-Pro firmware regression specific to the WPA handshake with ESP clients — it's U7-specific, since the identical devices are rock-solid on a U6-Pro (WiFi 6) and AC-Pro (WiFi 5), i.e. not "WiFi 6/7" in general.

Workaround: downgrade the U7's firmware and pin it (disable auto-update) until Ubiquiti fix it. In my case I went from 8.6.11 → 8.5.21.

  (Side note: there's a separate ESP32/lwIP bug where an incoming IPv6 RA carrying RDNSS overwrites the IPv4 DNS and DNS then hangs — see #5438. I hit that too and it's worth fixing, but it was not the cause of the disconnect loop — the loop was purely the U7 handshake.)

**Comment by jonny190** [comment]
This is a U7 firmware / ESP association bug — reproduced with a blank ESPHome config (no WLED involved).

  I hit the same thing (ESP32 WLED on a U7-Pro-Max, ~10–15 s connect/freeze loop) and chased it to the AP. The clincher: I flashed a stock ESPHome image (ESP32-S3, only SSID + password + fast_connect, nothing else) and pinned it to the
  U7 — it never associates, looping forever:

  [wifi_esp32] Disconnected ssid='…' reason='Auth Expired'
  [wifi_esp32] Disconnected reason='Authentication Failed'
  [wifi_esp32] Disconnected reason='Probe Request Unsuccessful'
  Connected: NO

  These are 802.11 auth-stage failures, and on the UniFi side the AP shows the matching pattern — it re-sends WPA 4-way-handshake msg 3/4, the ESP never returns 4/4, then wpa_auth_failures / deauth_reason 15 (4-Way-Handshake-timeout) /
  sta left:

  WPA: sending 3/4 msg of 4-Way Handshake
  WPA: sending 3/4 msg of 4-Way Handshake
  802.11: disassociated   wpa_auth_failures: 1   deauth_reason 15

  Since this reproduces with plain ESPHome, it's not a WLED bug at all. Supporting evidence from my setup:
  - Same ESP devices are rock-solid on a U6-Pro (WiFi 6) and a UAP-AC-Pro (WiFi 5) → 0 disconnects. So it's U7-specific, not "WiFi 6/7" generally.
  - Ruled out power (3 separate PSUs), airtime (~8% busy), roaming, and IPv6/RA/DNS (RA-free VLAN, still failed).
  - Downgrading the U7 firmware fixed it for older-ESP32 devices (0 disconnects, stable). (An ESP32-S3 still struggled in my latest test — possibly firmware-state-dependent.)

  TL;DR: ESP clients fail the WPA 4-way handshake on the U7-Pro/U7-Pro-Max — reproducible with stock ESPHome. Workaround: keep ESP devices on a non-U7 AP, or downgrade/pin the U7 firmware. This belongs upstream with Ubiquiti rather than
  as a WLED bug.

**Comment by wila91** [comment]
I have no issues whit my u7 pro running 8.6.11 using any of my esphome or wled (v15 or v16) devises 

Im using WPA-2 and Enhanced IoT Connectivity for my IoT devises.

**Comment by wila91** [comment]
Did not mean to reopen
